// Writes dist/sw.js after the Vite build: a small, dependency-free service
// worker that precaches everything the build produced, so the app keeps
// working offline. We hand-roll this instead of using a Workbox-based
// plugin (e.g. vite-plugin-pwa) because workbox-build's generated service
// worker embeds the project's absolute filesystem path as raw, unescaped
// import specifiers — this repo's path contains an apostrophe
// ("Calude_App's"), which breaks that generated JS outright.
//
// Cache name is derived from the build output itself (path + size of every
// file), so it only changes when the build actually changes — not on every
// deploy — and the old cache is cleaned up automatically on activate.
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const BASE = '/family-expense-tracker/';
const distDir = fileURLToPath(new URL('../dist/', import.meta.url));

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(distDir)
  .map((f) => relative(distDir, f).split('\\').join('/'))
  .filter((f) => f !== 'sw.js'); // don't precache the service worker itself

const manifest = files
  .map((f) => `${f}:${statSync(join(distDir, f)).size}`)
  .sort()
  .join('\n');
const version = createHash('sha256').update(manifest).digest('hex').slice(0, 12);

const precacheUrls = files.map((f) => JSON.stringify(BASE + f));

const swSource = `// Auto-generated by scripts/generate-sw.mjs — do not edit by hand.
const CACHE_NAME = 'family-expense-tracker-${version}';
const PRECACHE_URLS = [\n  ${precacheUrls.join(',\n  ')}\n];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(
        names
          .filter((name) => name.startsWith('family-expense-tracker-') && name !== CACHE_NAME)
          .map((name) => caches.delete(name)),
      ))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  // Navigations (and index.html directly) go network-first: online, this
  // always picks up whatever was just deployed and refreshes the cache with
  // it; offline, it falls back to the last cached version instead of
  // erroring or resurrecting something older from the browser's own HTTP
  // cache. ignoreVary skips a Vary: Origin comparison some static hosts add
  // — without it, the crossorigin script/link tags Vite emits send an
  // Origin header the original same-origin precache fetch didn't have, so
  // every cache lookup below would miss even though the entry is right there.
  const matchOpts = { ignoreVary: true };
  if (request.mode === 'navigate' || request.url.endsWith('/index.html')) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request, matchOpts).then((cached) => cached || caches.match('${BASE}index.html', matchOpts))),
    );
    return;
  }

  // Everything else (content-hashed JS/CSS/images) is safe to serve
  // cache-first — any real content change gets a new filename automatically.
  event.respondWith(
    caches.match(request, matchOpts).then((cached) => cached || fetch(request)),
  );
});
`;

mkdirSync(distDir, { recursive: true });
writeFileSync(join(distDir, 'sw.js'), swSource);
console.log(`Generated dist/sw.js (cache family-expense-tracker-${version}, ${files.length} precached files)`);
